github: add comment stats on issues and prs
psss/did pull request #283
Opened 2023-01-18 12:46 UTC by sandrobonazzola

Fixes: #128
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

2023-01-20 11:35 UTC, kwk requested changes
Can you please add a test for this?

2023-01-20 11:39 UTC, kwk commented
Thank you @sandrobonazzola for coming up with this PR. I think this will be a great addition to `did`.

2023-01-23 08:12 UTC, sandrobonazzola commented
> Can you please add a test for this?

Done

2023-01-27 14:36 UTC, kwk requested changes
Thank you @sandrobonazzola for this contribution and for adding the tests. I've proposed a small log message change but then I think this PR is good to be merged. I ran tests locally and all passed. @psss do you have anything against me merging this?

2023-01-27 14:36 UTC, kwk commented on did/plugins/github.py
> +        log.info("Searching for issues commented by {0}".format(self.user))
```suggestion
        log.info("Searching for issues commented on by {0}".format(self.user))
```

2023-01-27 14:36 UTC, kwk commented on did/plugins/github.py
> +        log.info("Searching for pull requests commented by {0}".format(
```suggestion
        log.info("Searching for pull requests commented on by {0}".format(
```

2023-01-27 14:42 UTC, sandrobonazzola commented
Log message fixes are ok for me

2023-01-27 14:46 UTC, kwk approved these changes
LGTM

2023-01-27 15:25 UTC, psss approved these changes
Thanks much for this improvement! Looks nice. I've just updated the commit message a bit to be aligned with the [recommendations](https://did.readthedocs.io/en/latest/contribute.html#commits).

2023-01-27 15:47 UTC, merged