allow skipping events that are not reportable
psss/did pull request #340
Opened 2023-11-16 14:12 UTC by xsuchy

e.g. lunch break, focus block, deadline reminders

2023-12-04 22:42 UTC, psss requested changes
Thanks for the improvement! Just two suggestions.

2023-12-04 22:42 UTC, psss commented on did/stats.py
> +    skip = None
This should not be needed. The `skip` option belongs to configuration and it doesn't have to be defined here.

2023-12-04 22:42 UTC, psss commented on did/plugins/google.py
> +        self.skip = config.get("skip")
```suggestion
        self.skip = config.get("skip", [])
```

To make it working when no `skip` is present.

2023-12-05 08:19 UTC, xsuchy commented
Updated.

2023-12-13 22:10 UTC, psss approved these changes
Thanks for the adjustments, now looks good. Just modified the [commit message](https://did.readthedocs.io/en/latest/contribute.html#commits) for a consistent changelog.

2023-12-13 22:49 UTC, merged