Changes to make it work on macOS Sonoma / Python 3.11
psss/did pull request #353
Opened 2024-01-06 23:56 UTC by ammachado

2025-05-19 12:27 UTC, sandrobonazzola commented
Can you please rebase? I think a fix for this has been already included in current main.

2025-05-21 08:41 UTC, sandrobonazzola requested changes

2025-05-21 08:41 UTC, sandrobonazzola commented on did/plugins/jira.py
> +from urllib3.exceptions import InsecureRequestWarning
I agree with dropping  `import urllib3.exceptions` as it's already covered by `import urllib3` but the `from urllib3.exceptions import InsecureRequestWarning` line is not needed.

2025-05-21 08:41 UTC, sandrobonazzola commented on .gitignore
> +.idea
Not really needed for the topic of the PR but no strong feelings about keeping it here or not.

2025-05-22 06:54 UTC, sandrobonazzola approved these changes
LGTM

2025-05-22 06:59 UTC, merged

2025-05-23 10:45 UTC, psss commented
@sandrobonazzola, one suggestion: Let's use squash when merging pull requests, so that `main` contains just the "interesting" comments. Does it work for you?